
services:
  app:
    build:
      context: ./
      dockerfile: ./src/misc/docker/app.dockerfile
      args:
        install_dev: 1
    image: ${DOCKER_IMAGE:-local/d7/wazzup}:${DOCKER_TAG:-latest}
    volumes:
      - ./:/app:rw
    