[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
skip = [".git"]
include_trailing_comma = true
multi_line_output = 7

[project]
name = "wazzup"
version = "0.1.2"
authors = [
  { name="Rafael model", email="rafael.model@d7.dev" },
]
description = "A python package for sending messages using the official Whatsapp API"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "requests>=2.25.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-mock>=3.14",
]

[project.urls]
Homepage = "https://github.com/7ws/wazzup"
Issues = "https://github.com/7ws/wazzup/issues"

[tool.ruff]
target-version = "py313"
line-length = 80
fix = true
exclude = [
  ".venv",
]

[tool.ruff.lint]
select = [
  "YTT",    # flake8-2020
  "S",      # flake8-bandit
  "B",      # flake8-bugbear
  "A",      # flake8-builtins
  "C4",     # flake8-comprehensions
  "T10",    # flake8-debugger
  "SIM",    # flake8-simplify
  "I",      # isort
  "C90",    # mccabe
  "E",      # pycodestyle
  "W",      # pycodestyle
  "F",      # pyflakes
  "PGH",    # pygrep-hooks
  "UP",     # pyupgrade
  "RUF",    # ruff
  "TRY",    # tryceratops
]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D106",
  "D203",
  "D212",
  "E501",
  "E731",
  "D",
  "S113",
  "TRY003",
  "UP046",
]

[tool.ruff.lint.per-file-ignores]
"**/{tests}/*" = ["S101", "S105", "S106", "S603"]
"__init__.py" = ["E402"]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"
